//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.21 at 10:55:09 AM CET 
//


package tcxml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Icon_QNAME = new QName("http://www.example.org/tcxml", "icon");
    private final static QName _Ident_QNAME = new QName("http://www.example.org/tcxml", "ident");
    private final static QName _TruScript_QNAME = new QName("http://www.example.org/tcxml", "truScript");
    private final static QName _Step_QNAME = new QName("http://www.example.org/tcxml", "step");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TruScript }
     * 
     */
    public TruScript createTruScript() {
        return new TruScript();
    }

    /**
     * Create an instance of {@link Step }
     * 
     */
    public Step createStep() {
        return new Step();
    }

    /**
     * Create an instance of {@link Transactions }
     * 
     */
    public Transactions createTransactions() {
        return new Transactions();
    }

    /**
     * Create an instance of {@link Ident }
     * 
     */
    public Ident createIdent() {
        return new Ident();
    }

    /**
     * Create an instance of {@link TestObjects }
     * 
     */
    public TestObjects createTestObjects() {
        return new TestObjects();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link Vertex }
     * 
     */
    public Vertex createVertex() {
        return new Vertex();
    }

    /**
     * Create an instance of {@link Roles }
     * 
     */
    public Roles createRoles() {
        return new Roles();
    }

    /**
     * Create an instance of {@link TestObject }
     * 
     */
    public TestObject createTestObject() {
        return new TestObject();
    }

    /**
     * Create an instance of {@link Idents }
     * 
     */
    public Idents createIdents() {
        return new Idents();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/tcxml", name = "icon")
    public JAXBElement<String> createIcon(String value) {
        return new JAXBElement<String>(_Icon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/tcxml", name = "ident")
    public JAXBElement<String> createIdent(String value) {
        return new JAXBElement<String>(_Ident_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TruScript }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/tcxml", name = "truScript")
    public JAXBElement<TruScript> createTruScript(TruScript value) {
        return new JAXBElement<TruScript>(_TruScript_QNAME, TruScript.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Step }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/tcxml", name = "step")
    public JAXBElement<Step> createStep(Step value) {
        return new JAXBElement<Step>(_Step_QNAME, Step.class, null, value);
    }

}
