//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.21 at 10:55:09 AM CET 
//


package tcxml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for step complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="step">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.org/tcxml}step" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="stepId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="action" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="section" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="actionName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="arguments" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="categoryName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="methodName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="snapshotId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="libName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="funcName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="testObject" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="recDuration" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="autoEndEventFF" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="activeStep" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="endEvent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="objectTimeout" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="catch" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NewAttribute" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="overwriteUI" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "step", propOrder = {
    "step"
})
public class Step {

    protected List<Step> step;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "stepId")
    protected String stepId;
    @XmlAttribute(name = "action")
    protected String action;
    @XmlAttribute(name = "level")
    protected String level;
    @XmlAttribute(name = "section")
    protected String section;
    @XmlAttribute(name = "actionName")
    protected String actionName;
    @XmlAttribute(name = "arguments")
    protected String arguments;
    @XmlAttribute(name = "index")
    protected String index;
    @XmlAttribute(name = "categoryName")
    protected String categoryName;
    @XmlAttribute(name = "methodName")
    protected String methodName;
    @XmlAttribute(name = "snapshotId")
    protected String snapshotId;
    @XmlAttribute(name = "libName")
    protected String libName;
    @XmlAttribute(name = "funcName")
    protected String funcName;
    @XmlAttribute(name = "testObject")
    protected String testObject;
    @XmlAttribute(name = "recDuration")
    protected String recDuration;
    @XmlAttribute(name = "autoEndEventFF")
    protected String autoEndEventFF;
    @XmlAttribute(name = "activeStep")
    protected String activeStep;
    @XmlAttribute(name = "endEvent")
    protected String endEvent;
    @XmlAttribute(name = "objectTimeout")
    protected String objectTimeout;
    @XmlAttribute(name = "catch")
    protected String _catch;
    @XmlAttribute(name = "NewAttribute")
    protected String newAttribute;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "overwriteUI")
    protected String overwriteUI;

    /**
     * Gets the value of the step property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the step property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Step }
     * 
     * 
     */
    public List<Step> getStep() {
        if (step == null) {
            step = new ArrayList<Step>();
        }
        return this.step;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the stepId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStepId() {
        return stepId;
    }

    /**
     * Sets the value of the stepId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStepId(String value) {
        this.stepId = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection(String value) {
        this.section = value;
    }

    /**
     * Gets the value of the actionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * Sets the value of the actionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionName(String value) {
        this.actionName = value;
    }

    /**
     * Gets the value of the arguments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArguments() {
        return arguments;
    }

    /**
     * Sets the value of the arguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArguments(String value) {
        this.arguments = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndex(String value) {
        this.index = value;
    }

    /**
     * Gets the value of the categoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * Sets the value of the categoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryName(String value) {
        this.categoryName = value;
    }

    /**
     * Gets the value of the methodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * Sets the value of the methodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodName(String value) {
        this.methodName = value;
    }

    /**
     * Gets the value of the snapshotId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnapshotId() {
        return snapshotId;
    }

    /**
     * Sets the value of the snapshotId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnapshotId(String value) {
        this.snapshotId = value;
    }

    /**
     * Gets the value of the libName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibName() {
        return libName;
    }

    /**
     * Sets the value of the libName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibName(String value) {
        this.libName = value;
    }

    /**
     * Gets the value of the funcName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuncName() {
        return funcName;
    }

    /**
     * Sets the value of the funcName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuncName(String value) {
        this.funcName = value;
    }

    /**
     * Gets the value of the testObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestObject() {
        return testObject;
    }

    /**
     * Sets the value of the testObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestObject(String value) {
        this.testObject = value;
    }

    /**
     * Gets the value of the recDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecDuration() {
        return recDuration;
    }

    /**
     * Sets the value of the recDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecDuration(String value) {
        this.recDuration = value;
    }

    /**
     * Gets the value of the autoEndEventFF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoEndEventFF() {
        return autoEndEventFF;
    }

    /**
     * Sets the value of the autoEndEventFF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoEndEventFF(String value) {
        this.autoEndEventFF = value;
    }

    /**
     * Gets the value of the activeStep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveStep() {
        return activeStep;
    }

    /**
     * Sets the value of the activeStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveStep(String value) {
        this.activeStep = value;
    }

    /**
     * Gets the value of the endEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndEvent() {
        return endEvent;
    }

    /**
     * Sets the value of the endEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndEvent(String value) {
        this.endEvent = value;
    }

    /**
     * Gets the value of the objectTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectTimeout() {
        return objectTimeout;
    }

    /**
     * Sets the value of the objectTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectTimeout(String value) {
        this.objectTimeout = value;
    }

    /**
     * Gets the value of the catch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatch() {
        return _catch;
    }

    /**
     * Sets the value of the catch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatch(String value) {
        this._catch = value;
    }

    /**
     * Gets the value of the newAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewAttribute() {
        return newAttribute;
    }

    /**
     * Sets the value of the newAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewAttribute(String value) {
        this.newAttribute = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the overwriteUI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverwriteUI() {
        return overwriteUI;
    }

    /**
     * Sets the value of the overwriteUI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverwriteUI(String value) {
        this.overwriteUI = value;
    }

}
