//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.21 at 10:55:09 AM CET 
//


package tcxml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="roles" type="{http://www.example.org/tcxml}roles"/>
 *         &lt;element name="idents" type="{http://www.example.org/tcxml}idents"/>
 *         &lt;element ref="{http://www.example.org/tcxml}icon" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="methods" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="testObjId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="autoName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="platform" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fallbackName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="manualName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testObject", propOrder = {
    "roles",
    "idents",
    "icon",
    "methods"
})
public class TestObject {

    @XmlElement(required = true)
    protected Roles roles;
    @XmlElement(required = true)
    protected Idents idents;
    protected List<String> icon;
    @XmlElement(required = true)
    protected String methods;
    @XmlAttribute(name = "testObjId")
    protected String testObjId;
    @XmlAttribute(name = "autoName")
    protected String autoName;
    @XmlAttribute(name = "platform")
    protected String platform;
    @XmlAttribute(name = "fallbackName")
    protected String fallbackName;
    @XmlAttribute(name = "manualName")
    protected String manualName;

    /**
     * Gets the value of the roles property.
     * 
     * @return
     *     possible object is
     *     {@link Roles }
     *     
     */
    public Roles getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Roles }
     *     
     */
    public void setRoles(Roles value) {
        this.roles = value;
    }

    /**
     * Gets the value of the idents property.
     * 
     * @return
     *     possible object is
     *     {@link Idents }
     *     
     */
    public Idents getIdents() {
        return idents;
    }

    /**
     * Sets the value of the idents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Idents }
     *     
     */
    public void setIdents(Idents value) {
        this.idents = value;
    }

    /**
     * Gets the value of the icon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIcon() {
        if (icon == null) {
            icon = new ArrayList<String>();
        }
        return this.icon;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethods(String value) {
        this.methods = value;
    }

    /**
     * Gets the value of the testObjId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestObjId() {
        return testObjId;
    }

    /**
     * Sets the value of the testObjId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestObjId(String value) {
        this.testObjId = value;
    }

    /**
     * Gets the value of the autoName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoName() {
        return autoName;
    }

    /**
     * Sets the value of the autoName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoName(String value) {
        this.autoName = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }

    /**
     * Gets the value of the fallbackName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFallbackName() {
        return fallbackName;
    }

    /**
     * Sets the value of the fallbackName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFallbackName(String value) {
        this.fallbackName = value;
    }

    /**
     * Gets the value of the manualName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManualName() {
        return manualName;
    }

    /**
     * Sets the value of the manualName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManualName(String value) {
        this.manualName = value;
    }

}
